## Matemática e Estatística aplicada para Data Science, Machjine Leaning e IA

#### Lab 3

### Regras Básicas da Álgebra, Operações com Vegtores e Algoritmo de Machine Learning

### Intalando e Carregando Pacotes

In [1]:
# Importações
import math
import numpy as np

In [ ]:
# Versões dos pacotes usados neste notebook
%reload_ext watermark
%watermark -a "DSA Algebra"

## Regras Básicas da Álgebra
> Propriedades da Igualdade

In [ ]:
# Reflexiva
# Qualquer número ou expressão é igual a si  mesmo

a = 5
print(a == a) # True

In [ ]:
# Simétrica
a = 5
b = 5
print(a == b) # True
print(b == a) # True

In [ ]:
# Transitiva
a = 5
b = 5
c = 5
print(a == b and b == c) # True
print(a == c) # True

> Propriedades das Operações

In [ ]:
# Comutativa (Adição e Multiplicação)
# A ordem dos números não afeta a soma ou o produto
a = 3
b = 4
print(a + b == b + a) # True
print(a * b == b * a) # True

In [ ]:
# Associativa (Adição e Multiplicação)
# A maneira como os nũemros são agrupados não agera a soma ou o produto
a = 3
b = 4
c = 5
print((a + b) + c == a + (b + c)) # True
print((a * b) * c == a * (b * c)) # True

In [ ]:
# Distributiva
a = 3
b = 4
c = 5
print(a * (b + c) == a * b + a * c) # True

> Elementos Neutros e Inversos

In [ ]:
# Elemento Neutro da Adição (0)
a = 7
print(a + 0 == a) # True

In [ ]:
# Elemento Netruo da Multiplicação (1)
a = 7
print(a * 1 == a) # True

In [ ]:
# Inverso Aditivo
a = 7
print(a + (-a) == 0) # True

In [ ]:
# Inverso Multiplicação
a = 7
print(a * (1/a) == 1) #True

> Regras de Expoinenciação

In [ ]:
# Produto de mesma Base
print(2**3 * 2**4 == 2**(3+4)) # True)

In [ ]:
# Divisão de mesma Base
print(2**5 / 2**2 == 2**(5-2)) # True

In [ ]:
# Potência de uma Potência
print((2**3)**2 == 2**(3*2)) # True

In [ ]:
# Potência de um produto
print((2*3)**2 == 2**2 * 3**2) # True

In [ ]:
# Exponencial Zero
print(2**0 == 1) # True

> Regras de Radicais

In [ ]:
# Raiz de um Produto ** ATENÇÃO AO CÁLCULO DO PONTO FLUTUANTE
print(math.sqrt(2*8) == math.sqrt(2) * math.sqrt(8)) # Tru

In [ ]:
# Vamos adicionar tolerância ao cálculo (afinal, o mundo precisa mesmo de mais tolerância !)
a = math.sqrt(2*8)
b = math.sqrt(2) * math.sqrt(8)
tolerance = 1e-10
print(abs(a - b) < tolerance)

In [ ]:
# Raiz de um Quociente
print(math.sqrt(16/4) == math.sqrt(16) / math.sqrt(4)) # True

> Regras de Polinômios (Adição e Subtração de Termos Semelhantes)

In [ ]:
# Regras de Polinômios (Adição e Subtração de Termos Semelhantes)

# Polinômios: 2x² + 3x + 4 e 3x² -2x + 1
# Adição: (2x² + 3x²) + (3x -2x + (4 + 1)

# Variável 
x = 2

# Calcula a Adição dos polonômios
print((2*x**2 + 3*x**2) + (3*x - 2*x) + (4+1))

> Regras de Frações

In [ ]:
# Multiplicação
# Frações: (1/2) + (3/4)
print((1/2) * (3/4)) # 0.375

In [ ]:
# Divisão
# Frações: (1/2 / (3/4) = (1/2) * 4/3)
print((1/2) / (3/4)) # 0.666

In [ ]:
# Soma e subtração com Denominador Comum:
# Frações (1/4) + (3/4)
print((1/4) + (3/4)) # 1.0

### Operações com Vetores - Adição e Subtração

In [ ]:
# Definindo dois vetores com listas
vetor_a = [3, 4, 5]
vetor_b = [1, 2, 3]

In [ ]:
# Função para Adição de vetores
def adicionar_vetores(a, b):
    return [a[i] + b[i] for i in range(len(a))]

In [ ]:
#Função para subtração de vetores
def subtrair_vetores(a, b):
    return[a[i] - b[i] for i in range(len(a))]

In [ ]:
# Realizando as operações
vetor_soma = adicionar_vetores(vetor_a, vetor_b)
vetor_diferenca = subtrair_vetores(vetor_a, vetor_b)

In [ ]:
# Mostrando os resultado
print(f"Vetor a: {vetor_a}")
print(f"Vetor b: {vetor_b}")
print(f"Soma dos vetores: {vetor_soma}")
print(f"Diferenca dos Vetores: {vetor_diferenca}")

### Operações com vetores - Cross Product (Produto Vetorial)

O Produto Vetorial entre dois vetores resulta em um terceiro vetor (um novo) que é perpendicular aos dois vetores originais.

https://www.wolframalpha.com/input/?i=cross+product+calculator
<br>
https://www.mathsisfun.com/algebra/vectors-cross-product.html

In [ ]:
# Função para calcular o produto vetorial entre 2 vetores
def produto_vetorial(v1, v2):
    x = v1[1] * v2[2] - v1[2] * v2[1]
    y = v1[2] * v2[0] - v1[0] * v2[2]
    z = v1[0] * v2[1] - v1[1] * v2[0]
    return [x, y, z]

In [ ]:
# Criação dos vetores
vetor_a = [2, -3, 1]
vetor_b = [5, 7, 6]

In [ ]:
# Calculando o produto Vetorial
resultado = produto_vetorial(vetor_a, vetor_b)
print(f"Produto Vetorial: {resultado}")

### Operações com Vetores - Dot Product (Produto Escalar)

O produto escalar de dois vetores é uma operação que resulta em um escalar (um número). Matematicamente é a soma dos produtos dos componentes corespondentes dos vetores. Resultando na simplificação dos resultaldos em um único valor

In [ ]:
# FFunção para calcular o produto escalar
def produto_escalar(v1, v2):
    return sum(a * b for a, b in zip(v1, v2))

In [ ]:
# Criação dos vetores
vetor_a = [2, -3, 1]
vetor_b = [5, 7, 6]

In [ ]:
zipa = zip(vetor_a, vetor_b)
print(zipa)

In [ ]:
# Calculando o produto Vetorial
resultado = produto_escalar(vetor_a, vetor_b)
print(f"Produto Vetorial: {resultado}")

### Machine Learning apenas com operações Matemáticas (sem uso de Frameworks)

Vamos criar um modelo capaz de prever o preço de um ativo financeiro com base na texa nominal de juros.

In [2]:
# Gerando dados sint[eticos
np.random.seed(0)
X = np.random.randint(1, 10, size = (100, 1)) # Cria 100 instancias, valores entre 1 e 10
y = 50000 + 30000 * X + np.random.randn(100, 1) * 15000 # Relação linear: preço base + preço por ativo + ruído

In [3]:
# Visualizando alguns registros
X[1:5]

array([[1],
       [4],
       [4],
       [8]])

In [4]:
# Visualizando Alguns registros
y[1:5]

array([[ 85385.04146705],
       [186141.81556278],
       [172882.11251578],
       [302793.88936252]])

In [5]:
# Adicionar coluna de uns para o termo de interceptação
X_b = np.c_[np.ones((100, 1)), X] # Adiciona x0 = 1 a cada instancia

#### Função de Custo MSE com Operações entre Vetores

Esta função compute_cost é uma implementação da função de custo de erro quadrático médio, que é amplamente usada em regressão linear. O objetivo dessa função é medir quão bem o modelo de regressão (representado pelos parâmetros theta) está desempenhando em relação ao conjunto de dados (X e y). Um custo mais baixo indica que o modelo está fazendo previsões mais precisas

In [6]:
# Função de Custo MSE com Operações entre Vetores
def func_cost(X, y, theta):
    # m é o nnúmero de exemplos de treinamento (observações) no conjunto de dados
    m = len(y)

    # Calcula a função de custo para a regressão linear
    # Afunção de custo é a média dos erros quadrados entre as previsões e os valores reais
    # (1/(2*m) é um fator de escala comum em função de custo de erro quadxrático médio
    # np.sum(np.square(X.dot(theta) - y)) é a soma dos quadrados dos erros
    # X.dot(theta) é o produto matricial de X (dados qe entreda) e theta) (parâmetros do modelo)
    # X.dot(theta) - y é a diferença entre as previsões e os valores reais
    cost = (1/(2*m)) * np.sum(np.square(X.dot(theta) - y))

    # Retorna o custo calculado
    return cost

### Algoritmo Gradiente Descendente com Operações entre Vetores

In [12]:
# Gradiente descendente
def gradiente_decent(X, y, theta, learning_rate, iterations):

    # m é o numero de exemplos de treinamento no conujunto de dados
    m = len(y)

    # Inicializa um array para armazenar o histórico de custo em cada iteração
    cost_history = np.zeros(iterations)

    # Loop para realizar o número especificado de iterações
    for i in range(iterations):
        # Calcula o gradiente da função de custo em relação a theta
        # O gradiente é a média dos produtos dos erros e as características de entrada
        gradients = 1/m * X.T.dot(X.dot(theta) - y)

        # Atualiza os parâmetros theta subtraindo o produto da taxa de aprendizado e o gradiente
        # Esta é a etapa de descida do gradiente, movendo-se em direção ao mínimo da função de custo
        theta = theta - learning_rate * gradients

        # Calcula o custo com o theta atualizado e armazena no histórico de custo
        cost_history[i] = func_cost(X, y, theta)

    # Retorna os parâmetros theta otimizados e o histórico de custo
    return theta, cost_history

#### Treinamento do Modelo

In [8]:
# Parâmetros iniciais

# Inicia os parâmetros randomicamente
theta = np.random.randn(2, 1)

# Taxa de aprendizado
learning_rate = 0.01

# Número de passadas de treino
iterations = 1000

In [13]:
# Treinando o modelo
theta_final, cost_history = gradiente_decent(X_b, y, theta, learning_rate, iterations)

In [14]:
print(f"Modelo de Machine Leaning - Parâmetros Finais>\n", theta_final)

Modelo de Machine Leaning - Parâmetros Finais>
 [[44287.25556464]
 [31108.64267429]]


#### Deploy e Previsão com Novos Dados

In [17]:
# Novo Valor de X
X_new = np.array([[4.5]])

In [18]:
# Novo valor do bias
X_new_b = np.c_[np.ones((1, 1)), X_new]

In [19]:
# PRevisão
y_predict = X_new_b.dot(theta_final)

In [20]:
print(f"Com base na taxa de juros nominal, esta é a previsão do preço do ativo:", np.round(y_predict, 2))

Com base na taxa de juros nominal, esta é a previsão do preço do ativo: [[184276.15]]
